_: &language_go_1_12
  name: "go 1.12"
  language: go
  go: "1.12.x"
_: &language_go_1_13
  name: "go 1.13"
  language: go
  go: "1.13.x"
_: &language_js
  language: node_js
  node_js: "lts/*"

_: &gen_link_kyber
  pushd external/js/kyber && npm ci && npm run link && popd
_: &get_go
  - gimme 1.12.10
  - . $HOME/.gimme/envs/go1.12.10.env

_: &stage_lint_go
  script:
    - make -C conode verify
    - GO111MODULE=on make test_{fmt,lint}
_: &stage_build_go
  script:
    - make -C conode bindist tooldist
    - GO111MODULE=on go build ./...
_: &stage_test_go
  script: GO111MODULE=on make test_goveralls
_: &stage_deploy_npm
  <<: *language_js
  before_deploy: echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > $HOME/.npmrc
  script: skip  # default to `make test`

dist: trusty

stages:
  - lint
  - build
  - test
  - deploy

jobs:
  include:
    - stage: lint
      name: "protobuf"
      language: minimal
      script: make test_proto
    - <<: *stage_lint_go
      <<: *language_go_1_13

    - stage: build
      <<: *stage_build_go
      <<: *language_go_1_12
    - <<: *stage_build_go
      <<: *language_go_1_13

    - name: "js > kyber"
      <<: *language_js
      script:
        - cd external/js/kyber
        - npm ci
        - npm run build
    - name: "js > cothority"
      <<: *language_js
      script:
        - *gen_link_kyber
        - cd external/js/cothority
        - npm ci
        - npm link @dedis/kyber
        - npm run build

    - stage: test
      <<: *language_go_1_13
      <<: *stage_test_go
    - name: "java"
      language: java
      install: *get_go
      script: make test_java
    - name: "js > kyber"
      <<: *language_js
      script:
        - cd external/js/kyber
        - npm ci
        - npm run test
    - name: "js > cothority"
      <<: *language_js
      install: *get_go
      before_script:
        - make docker
        - *gen_link_kyber
      script:
        - cd external/js/cothority
        - npm ci
        - npm link @dedis/kyber
        - npm run test

    - stage: deploy
      name: "NPM: js > kyber"
      <<: *stage_deploy_npm
      deploy:
        on:
          branch: master
        provider: script
        script: >-
          cd external/js/kyber &&
          npm ci &&
          npm version prerelease --preid=p`date +%y%m.%d%H.%M%S` &&
          ./publish.sh --tag dev
    - name: "NPM: js > cothority"
      <<: *stage_deploy_npm
      deploy:
        on:
          branch: master
        provider: script
        script: >-
          cd external/js/kyber && npm ci && npm run link && cd ../../.. &&
          cd external/js/cothority &&
          npm ci &&
          npm link @dedis/kyber &&
          npm version prerelease --preid=p`date +%y%m.%d%H.%M%S` &&
          ./publish.sh --tag dev

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
