_: &language_go_1_11
  name: "go 1.11"
  language: go
  go: "1.11.x"
_: &language_go_1_12
  name: "go 1.12"
  language: go
  go: "1.12.x"
_: &language_js
  language: node_js
  node_js: "lts/*"

_: &get_coding
  b=github.com/dedis/Coding; git clone https://$b.git $GOPATH/src/$b
_: &gen_link_kyber
  pushd external/js/kyber && npm ci && npm run link && popd
_: &get_go
  - gimme 1.12.4
  - . $HOME/.gimme/envs/go1.12.4.env

_: &stage_lint_go
  before_script: *get_coding
  script:
    - make -C conode verify
    - GO111MODULE=on make test_{fmt,lint}
_: &stage_build_go
  script:
    - make -C conode bindist
    - GO111MODULE=on go get ./...
    - GO111MODULE=on go build ./...
_: &stage_test_go
  before_script: *get_coding
  script: GO111MODULE=on make test_goveralls
_: &stage_deploy_npm
  <<: *language_js
  script: 
    - CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
    - JS_COTHORITY_N=`echo "$CHANGED_FILES" | grep -E -c "^external/js/cothority/" || true`
    - JS_KYBER_N=`echo "$CHANGED_FILES" | grep -E -c "^external/js/kyber/" || true`
  before_deploy: echo "//registry.npmjs.org/:_authToken=${DEPLOY_NPM_TOKEN}" > $HOME/.npmrc


dist: trusty

stages:
  - lint
  - build
  - test
  - deploy

jobs:
  include:
    - stage: lint
      name: "protobuf"
      language: minimal
      before_script: *get_coding
      script: make test_proto
    - <<: *stage_lint_go
      <<: *language_go_1_11
    - <<: *stage_lint_go
      <<: *language_go_1_12

    - stage: build
      <<: *stage_build_go
      <<: *language_go_1_11
    - <<: *stage_build_go
      <<: *language_go_1_12

    - name: "js > kyber"
      <<: *language_js
      script:
        - cd external/js/kyber
        - npm ci
        - npm run build
    - name: "js > cothority"
      <<: *language_js
      script:
        - *gen_link_kyber
        - cd external/js/cothority
        - npm ci
        - npm link @dedis/kyber
        - npm run build

    - stage: test
      <<: *stage_test_go
      <<: *language_go_1_11
    - <<: *stage_test_go
      <<: *language_go_1_12
    - name: "java"
      language: java
      install: *get_go
      before_script: *get_coding
      script: make test_java
    - name: "js > kyber"
      <<: *language_js
      script:
        - cd external/js/kyber
        - npm ci
        - npm run test
    - name: "js > cothority"
      <<: *language_js
      install: *get_go
      before_script:
        - *get_coding
        - make docker
        - *gen_link_kyber
      script:
        - cd external/js/cothority
        - npm ci
        - npm link @dedis/kyber
        - npm run test

    - stage: deploy
      name: "NPM: js > kyber"
      <<: *stage_deploy_npm
      deploy:
        on:
          branch: master
          condition: $JS_KYBER_N != 0
        provider: script
        script: >-
          cd external/js/kyber &&
          npm ci &&
          npm version prerelease --preid=p`date +%y%m.%d%H.%M%S` &&
          ./publish.sh --tag dev
    - name: "NPM: js > cothority"
      <<: *stage_deploy_npm
      deploy:
        on:
          branch: master
          condition: $JS_COTHORITY_N != 0
        provider: script
        script: >-
          cd external/js/kyber && npm ci && npm run link && cd ../../.. &&
          cd external/js/cothority &&
          npm ci &&
          npm link @dedis/kyber &&
          npm version prerelease --preid=p`date +%y%m.%d%H.%M%S` &&
          ./publish.sh --tag dev

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
